name: 'dbt_stackexchange_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

sources:
  dbt_stackexchange_project:
    +freshness:
      warn_after:
        count: 2
        period: day
      error_after:
        count: 3
        period: day

models:
  dbt_stackexchange_project:
    +materialized: table

    staging:
      +materialized: view

    intermediate:
      +materialized: table
